---
# Main
- name: "prometheus_exporter: main"
  block:
    - name: "prometheus_exporter: init vars"
      include_tasks: "{{ role_path }}/includes/vars.yml"

    - name: "prometheus_exporter: init pre_tasks"
      include_tasks: "{{ role_path }}/includes/pre_tasks.yml"

    - name: "prometheus_exporter: init pre_roles"
      include_tasks: "{{ role_path }}/includes/pre_roles.yml"

    - name: "prometheus_exporter: init tasks"
      include_tasks: "{{ role_path }}/includes/tasks.yml"

  rescue:
    - name: "prometheus_exporter: init rescue tasks"
      include_tasks: "{{ role_path }}/includes/rescue_tasks.yml"

    - name: "prometheus_exporter: init rescue roles"
      include_tasks: "{{ role_path }}/includes/rescue_roles.yml"

  always:
    - name: "prometheus_exporter: init post tasks"
      include_tasks: "{{ role_path }}/includes/post_tasks.yml"

    - name: "prometheus_exporter: init post roles"
      include_tasks: "{{ role_path }}/includes/post_roles.yml"
  when: type in supported_types