# Manage ServiceMonitor
---
- name: Get information about existing api-groups in the cluster for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: Convert serviceMonitor.enabled boolean var into ansible service_monitor_state state var for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  set_fact:
    service_monitor_state: "absent"
  when: service_monitor.enabled is defined and service_monitor.enabled|bool == false

- name: Manage ServiceMonitor (if monitoring.coreos.com api-group exists) for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    state: "{{ service_monitor_state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.api_exists | default(True)
  loop:
    - name: servicemonitor.yml.j2
      api_exists: "{{ True if 'monitoring.coreos.com' in api_groups else False }}"
